Repository tuwien-csd/damap-frontend, pull requests merged in 2022-12, with the labels that each got.

#69 remove 4000 characters input limit for automatically loaded datasets,
  libs/damap/src/lib/components/dmp/project/manual-project-input/manual-project-input.component.ts
  libs/damap/src/lib/services/form.service.ts
Labels: bug

#70 Add DMP editors
  apps/damap-frontend-e2e/cypress.config.ts
  apps/damap-frontend-e2e/src/e2e/access.cy.ts
  apps/damap-frontend-e2e/src/e2e/dmp.cy.ts
  libs/damap/src/assets/i18n/access/de.json
  libs/damap/src/assets/i18n/access/en.json
  libs/damap/src/assets/i18n/http/en.json
  libs/damap/src/assets/i18n/plans/en.json
  libs/damap/src/index.ts
  libs/damap/src/lib/components/access/access.component.css
  libs/damap/src/lib/components/access/access.component.html
  libs/damap/src/lib/components/access/access.component.spec.ts
  libs/damap/src/lib/components/access/access.component.ts
  libs/damap/src/lib/components/dmp/dmp.module.ts
  libs/damap/src/lib/components/dmp/dmp.routes.ts
  libs/damap/src/lib/components/plans/plans.component.ts
  libs/damap/src/lib/domain/access.ts
  libs/damap/src/lib/domain/contributor.ts
  libs/damap/src/lib/mocks/access-mocks.ts
  libs/damap/src/lib/services/backend.service.spec.ts
  libs/damap/src/lib/services/backend.service.ts
  libs/damap/src/lib/widgets/dmp-table/dmp-table.component.html
  libs/damap/src/lib/widgets/person-card/person-card.component.css
  libs/damap/src/lib/widgets/person-card/person-card.component.html
  libs/damap/src/lib/widgets/person-card/person-card.component.spec.ts
  libs/damap/src/lib/widgets/person-card/person-card.component.ts
Labels: enhancement, major

#78 Add access info
  libs/damap/src/assets/i18n/access/en.json
  libs/damap/src/lib/components/access/access.component.html
  libs/damap/src/lib/widgets/dmp-table/dmp-table.component.html
Labels: quality of life
